services:
  s3-storage:
    image: localstack/localstack:latest
    container_name: 'processor-s3-storage'
    ports:
      - '4566:4566'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=S3RVER
      - AWS_SECRET_ACCESS_KEY=S3RVER
    volumes:
      - ./volumes/s3-storage/localstack-script.sh:/etc/localstack/init/ready.d/script.sh
      - /var/run/docker.sock:/var/run/docker.sock

  mysql-db:
    image: mysql:5.7
    container_name: 'processor-mysql-db'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'transactions'
      MYSQL_USER: 'goferProcessor'
    volumes:
      - ./volumes/mysql-db:/docker-entrypoint-initdb.d
    expose:
      - '3306'
