app: transaction-processor
service: transaction-processor

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  timeout: 60
  stage: local
  environment:
    S3Bucket: "transaction-processor-bucket"
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3Bucket}"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3Bucket}/*"

custom:
  serverless-offline:
    noPrependStageInUrl: true
    useDocker: true
    httpPort: 4007
  s3:
    host: localhost
    directory: ../source

package:
  patterns:
    - "!*/**"
    - "bin/**"

functions:
  list:
    handler: bin/processor
    package:
      include:
        - ./bin/processor
    events:
      - http:
          path: /processor/{accountId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                accountId: true

resources:
  Resources:
    TransactionProcessorBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: transaction-processor-bucket
